server:
  port: 610

spring:
  application:
    name: user-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/users?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
    show-sql: true
    database: mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: 43.201.230.55
    port: 6379
    password: ${REDIS_PASSWORD}
  jwt:
    secret: c29jaWFsLW1lZGlhLXNwcmluZy1wcm9qZWN0LWJ5LWh5b2Jpbi15ZW9uZ3l1bHJvcmkK

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  config: classpath:logback-spring.xml

feign:
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always