pipeline {
    agent any

    stages {

        stage('Environment Setup') {
            steps {
                script {
                    sh 'chmod +x ./gradlew'
                    def projectName = sh(script:'./gradlew -q printProjectName', returnStdout:true).trim()
                    def projectVersion = sh(script:'./gradlew -q printProjectVersion', returnStdout:true).trim()
                    env.PROJECT_NAME = projectName
                    env.PROJECT_VERSION = projectVersion
                    env.JAR_PATH = "${WORKSPACE}/${env.PROJECT_NAME}/build/libs/${env.PROJECT_NAME}-${env.PROJECT_VERSION}.jar"
                }
                echo 'Environment variables set'
            }
        }

        stage('Test') {
            steps {
                dir("${WORKSPACE}") {
                    sh "./gradlew :${env.PROJECT_NAME}:test"
                }
                echo 'Tests complete'
            }
        }

        stage('Build') {
            steps {
                sh "chmod u+x ${WORKSPACE}/gradlew"
                dir("${WORKSPACE}") {
                    sh "./gradlew :${env.PROJECT_NAME}:clean :${env.PROJECT_NAME}:build -x test"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def cacheBust = sh(script: 'date +%s', returnStdout: true).trim()
                    def dockerImageTag = "${env.PROJECT_NAME}:${env.PROJECT_VERSION}-${cacheBust}"
                    sh "docker system prune -a -f"
                    sh "docker rmi $DOCKER_HUB_USER_NAME/${dockerImageTag} || true"
                    sh "docker build --no-cache=true --build-arg CACHEBUST=${cacheBust} -t ${dockerImageTag} -f ${WORKSPACE}/${env.PROJECT_NAME}/Dockerfile ${WORKSPACE}/${env.PROJECT_NAME}/build/libs/"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'DOCKER_HUB_ACCESS_TOKEN', variable: 'DOCKER_HUB_ACCESS_TOKEN')]) {
                        sh '''
                        echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USER_NAME --password-stdin
                        '''
                    }

                    def cacheBust = sh(script: 'date +%s', returnStdout: true).trim()
                    def dockerImageTag = "${env.PROJECT_NAME}:${env.PROJECT_VERSION}-${cacheBust}"
                    sh "docker tag ${dockerImageTag} $DOCKER_HUB_USER_NAME/${dockerImageTag}"
                    sh "docker push $DOCKER_HUB_USER_NAME/${dockerImageTag}"
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                script {
                    withCredentials([
                        sshUserPrivateKey(credentialsId: 'EC2_DEPLOY_KEY', keyFileVariable: 'EC2_DEPLOY_KEY'),
                        string(credentialsId: 'DB_ROOT_PASSWORD', variable: 'DB_ROOT_PASSWORD'),
                        string(credentialsId: 'DB_USER_NAME', variable: 'DB_USER_NAME'),
                        string(credentialsId: 'DB_USER_PASSWORD', variable: 'DB_USER_PASSWORD')
                    ]) {
                        sh '''
                        scp -i "$EC2_DEPLOY_KEY" ${PROJECT_NAME}/set-up-docker.sh ubuntu@"$EC2_IP":"$EC2_DEPLOY_PATH"
                        '''
                        sh '''
                        scp -i "$EC2_DEPLOY_KEY" "$JAR_PATH" ubuntu@"$EC2_IP":"$EC2_DEPLOY_PATH"
                        '''
                        sh '''
                        scp -i "$EC2_DEPLOY_KEY" "${WORKSPACE}/${PROJECT_NAME}/deploy.sh" "${WORKSPACE}/${PROJECT_NAME}/check-and-restart.sh" ubuntu@"$EC2_IP":"$EC2_DEPLOY_PATH"
                        '''
                        sh '''
                        ssh -i "$EC2_DEPLOY_KEY" ubuntu@"$EC2_IP" "chmod +x ${EC2_DEPLOY_PATH}/deploy.sh"
                        '''
                        sh '''
                        ssh -i "$EC2_DEPLOY_KEY" ubuntu@"$EC2_IP" "chmod +x ${EC2_DEPLOY_PATH}/set-up-docker.sh && ${EC2_DEPLOY_PATH}/set-up-docker.sh $DB_ROOT_PASSWORD $DB_USER_NAME $DB_USER_PASSWORD"
                        '''
                        sh '''
                        ssh -i "$EC2_DEPLOY_KEY" ubuntu@"$EC2_IP" "export DOCKER_HUB_USER_NAME='$DOCKER_HUB_USER_NAME'; export DB_USER_NAME='$DB_USER_NAME'; export DB_USER_PASSWORD='$DB_USER_PASSWORD'; export EC2_IP='$EC2_IP'; export REDIS_PASSWORD='$REDIS_PASSWORD'; export JWT_SECRET_KEY='$JWT_SECRET_KEY'; export PROJECT_NAME='$PROJECT_NAME'; export PROJECT_VERSION='$PROJECT_VERSION'; ${EC2_DEPLOY_PATH}/deploy.sh"
                        '''
                    }
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts:"${env.PROJECT_NAME}/build/libs/*.jar", fingerprint:true
                echo 'Artifacts archived'
            }
        }

    }
}
